<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
	  <PackageReference Include="Microsoft.OpenApi" Version="[2.11.0]" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="1.4.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Ultima">
      <HintPath>..\Ultima.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UltimaAPI.Tests" />
  </ItemGroup>

</Project>
